const fs = require("fs-extra");
const path = require("path");
const crypto = require("crypto");
const { getBrowser } = require("../utils/browserUtils");
const File = require("../models/File");

/**
 * @desc    Generate PDF from HTML text
 * @route   POST /api/speech-to-pdf/generate
 * @access  Public
 */
exports.generatePdfFromText = async (req, res, next) => {
    try {
        const { text, title = "Speech to Text Export", description = "" } = req.body;

        if (!text) {
            return res.status(400).json({
                success: false,
                message: "Please provide text content",
            });
        }

        const fileName = `speech_${crypto.randomUUID()}.pdf`;
        const outputPath = path.join(__dirname, "../outputs", fileName);

        // Ensure outputs directory exists
        await fs.ensureDir(path.join(__dirname, "../outputs"));

        const descriptionHtml = description 
            ? `<div class="description" style="font-size: 14px; color: #64748b; margin-bottom: 30px; font-style: italic; background: #f8fafc; padding: 15px; border-left: 4px solid #3b82f6; border-radius: 4px;">${description}</div>` 
            : "";

        // Construct HTML content for Puppeteer
        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    * {
                        box-sizing: border-box;
                    }
                    body {
                        font-family: 'Helvetica', 'Arial', sans-serif;
                        padding: 40px;
                        color: #334155;
                        line-height: 1.6;
                        max-width: 100%;
                        overflow-x: hidden;
                    }
                    .header {
                        text-align: center;
                        margin-bottom: 20px;
                        border-bottom: 2px solid #e2e8f0;
                        padding-bottom: 20px;
                    }
                    .title {
                        font-size: 28px;
                        font-weight: bold;
                        color: #1e293b;
                        margin-bottom: 10px;
                        text-transform: uppercase;
                    }
                    .date {
                        font-size: 12px;
                        color: #64748b;
                    }
                    .content {
                        font-size: 14px;
                        text-align: justify;
                        word-wrap: break-word;
                        white-space: pre-wrap;
                        overflow-wrap: break-word;
                        width: 100%;
                    }
                    .footer {
                        position: fixed;
                        bottom: 0;
                        left: 0;
                        right: 0;
                        text-align: center;
                        font-size: 10px;
                        color: #94a3b8;
                        padding: 20px;
                    }
                    p { 
                        margin-bottom: 15px; 
                        word-wrap: break-word;
                        white-space: pre-wrap; 
                        max-width: 100%;
                    }
                    h1 { color: #1e293b; font-size: 20px; }
                    h2 { color: #334155; font-size: 18px; }
                    h3 { color: #475569; font-size: 16px; }
                    ul, ol { margin-bottom: 15px; padding-left: 20px; }
                    li { margin-bottom: 5px; }
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="title">${title}</div>
                    <div class="date">Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</div>
                </div>
                ${descriptionHtml}
                <div class="content">
                    ${text}
                </div>
                <div class="footer">
                    Generated by VoicePDF AI Tools
                </div>
            </body>
            </html>
        `;

        // Launch Browser using robust utility
        const browser = await getBrowser();

        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: "networkidle0" });
        
        const pdfBuffer = await page.pdf({
            format: "A4",
            margin: {
                top: "20mm",
                bottom: "20mm",
                left: "20mm",
                right: "20mm"
            },
            printBackground: true
        });

        await browser.close();
        await fs.writeFile(outputPath, pdfBuffer);

        // API Response and File Tracking
        const protocol = req.protocol;
        const host = req.get("host");
        const downloadUrl = `${protocol}://${host}/outputs/${fileName}`;

        await File.create({
            filename: fileName,
            originalName: title + ".pdf",
            path: outputPath,
            size: (await fs.stat(outputPath)).size,
            mimeType: "application/pdf",
            operation: "convert",
            status: "completed",
            user: req.user ? req.user._id : undefined,
            guestId: req.user ? undefined : req.headers['x-guest-id']
        });
        
        res.status(200).json({
            success: true,
            data: {
                fileName,
                downloadUrl,
            },
        });

    } catch (error) {
        console.error("PDF Export Error:", error);
        next(error);
    }
};
