// Master list of tools from landingData.ts for daily blog generation
const ALL_TOOLS = [
    ['Merge PDF', 'pdf', 'Combine multiple PDF documents into one single file online for free.', '/merge-pdf'],
    ['Split PDF', 'pdf', 'Separate PDF pages or extract individual pages into standalone PDFs.', '/split-pdf'],
    ['Compress PDF', 'pdf', 'Shrink PDF file size while retaining crystal clear image & text quality.', '/compress-pdf'],
    ['Advanced PDF Editor', 'pdf', 'Annotate, add text, draw, and modify PDF pages directly in your browser.', '/editor'],
    ['Protect PDF', 'pdf', 'Encrypt your PDF documents with secure password protection.', '/protect-pdf'],
    ['Unlock PDF', 'pdf', 'Decrypt password-protected PDFs and remove security restrictions.', '/pdf-unlock'],
    ['Rotate PDF', 'pdf', 'Rotate PDF pages clockwise or counter-clockwise instantly.', '/rotate-pdf'],
    ['PDF to Image', 'pdf', 'Convert PDF pages into high-resolution PNG, JPG, or WebP images.', '/pdf-to-image'],
    ['PDF to Word', 'docs', 'Convert PDF documents into editable Microsoft Word (.docx) format.', '/pdf-to-word'],
    ['Word to PDF', 'docs', 'Transform Word (.docx) files into clean, professional PDF documents.', '/word-to-pdf'],
    ['PDF to Excel', 'docs', 'Extract data tables from PDF files into formatted Excel (.xlsx) sheets.', '/pdf-to-excel'],
    ['PowerPoint to PDF', 'docs', 'Convert presentation slides (.pptx) into standard PDF documents.', '/ppt-to-pdf'],
    ['HTML to PDF', 'docs', 'Convert web page URLs or raw HTML code into downloadable PDF files.', '/html-to-pdf'],
    ['PDF to HTML', 'docs', 'Export PDF document content into responsive web HTML pages.', '/pdf-to-html'],
    ['PDF to Text', 'docs', 'Extract raw plain text from PDF pages quickly and accurately.', '/pdf-to-text'],
    ['Text to PDF', 'docs', 'Create formatted PDF documents from plain text input.', '/text-to-pdf'],
    ['CSV to PDF', 'docs', 'Transform CSV tabular files into clean, organized PDF spreadsheets.', '/csv-to-pdf'],
    ['PDF to CSV', 'docs', 'Extract tables and data rows from PDF files into CSV format.', '/pdf-to-csv'],
    ['PDF to Speech', 'docs', 'Convert PDF text into natural-sounding voiceover audio narration.', '/pdf-to-speech'],
    ['Speech to PDF', 'docs', 'Transcribe live speech and voice recordings into a formatted PDF document.', '/speech-to-pdf'],
    ['Video to PDF Notes', 'docs', 'Extract key slide frames and visuals from video lectures into study notes.', '/video-to-pdf'],
    ['Audio to Transcript', 'docs', 'Transcribe audio recordings into clean editable text transcripts.', '/audio-to-transcript'],
    ['Image Resizer', 'image', 'Resize image dimensions (PNG, JPG, WebP) by pixels or percentages for free.', '/image-resizer'],
    ['Image Cropper', 'image', 'Crop photos with standard aspect ratios or custom crop frames online.', '/image-cropper'],
    ['Image Converter', 'image', 'Convert between HEIC, JPG, PNG, WEBP, and GIF image formats.', '/image-converter'],
    ['Image to SVG', 'image', 'Vectorize pixel images into scalable vector graphics (SVG).', '/svg'],
    ['Convert to JPG', 'image', 'Convert any image format to standard compressed JPEG format.', '/convert-to-jpg'],
    ['Convert to PNG', 'image', 'Convert images to lossless transparent PNG format.', '/convert-to-png'],
    ['AI Resume Builder', 'ai', 'Create a job-winning resume with AI suggestions and customizable templates.', '/resume-builder'],
    ['Pro AI Chart & Diagram Maker', 'ai', 'Generate flowcharts, DFDs, BPMN, and logic diagrams effortlessly with AI.', '/drowChart'],
    ['Base64 Encoder/Decoder', 'dev', 'Encode plain text or files to Base64 data strings and decode back.', '/base64'],
    ['JWT Decoder', 'dev', 'Decode and inspect JSON Web Tokens (JWT) client-side in real-time.', '/jwt'],
    ['JSON Formatter', 'dev', 'Pretty print, format, validate, and minify JSON data structures.', '/json-formatter'],
    ['JSON Validator', 'dev', 'Validate JSON syntax structure with precise error line highlights.', '/json-validator'],
    ['JSON Diff Checker', 'dev', 'Compare two JSON files or strings side-by-side with color diffs.', '/json-diff'],
    ['YAML ↔ JSON Converter', 'dev', 'Convert YAML code to JSON format and JSON data to clean YAML.', '/yaml-json'],
    ['CSV ↔ JSON Converter', 'dev', 'Convert CSV tabular data to JSON arrays and JSON to CSV spreadsheets.', '/csv-json'],
    ['Regex Tester', 'dev', 'Test regular expression patterns in real-time with regex match highlights.', '/regex-tester'],
    ['XML Formatter & Validator', 'dev', 'Beautify XML tags, format indentation, and check for XML syntax errors.', '/xml-tool'],
    ['SQL Formatter', 'dev', 'Pretty print SQL queries, capitalize keywords, and clean up query scripts.', '/sql-formatter'],
    ['Visual SQL Query Builder', 'dev', 'Construct complex SQL queries visually for SELECT, INSERT, UPDATE, and DELETE.', '/sql-query-builder'],
    ['Markdown Editor & HTML Converter', 'dev', 'Write Markdown with real-time preview and export to styled HTML.', '/markdown-editor'],
    ['Unified Code Minifier', 'dev', 'Minify JavaScript, CSS, and HTML code client-side to boost web performance.', '/code-minifier'],
    ['Precision OCR', 'ocr', 'Extract text from scanned documents and images in over 100 languages.', '/ocr'],
    ['PDF Watermark', 'pdf', 'Add custom text or image watermarks to PDF pages for copyright protection.', '/pdf-watermark'],
    ['PDF Page Numberer', 'pdf', 'Add page numbers to your PDF documents with customizable styling.', '/pdf-number'],
    ['SVG to Image', 'image', 'Rasterize SVG vector files into high-quality PNG, JPG, or WebP images.', '/svg-to-image'],
    ['Image Watermark', 'image', 'Add text or logo watermarks to photos and images online.', '/image-watermark'],
    ['UUID & Hash Generator', 'dev', 'Generate MD5, SHA-1, SHA-256 hashes, and random UUID v4 strings.', '/hash-generator'],
    ['URL Encoder & Parser', 'dev', 'Encode and decode URLs, search query params, and URI components.', '/url-encoder'],
    ['JSON to XML Converter', 'dev', 'Convert JSON payloads into clean, well-formed XML documents.', '/json-to-xml'],
    ['PDF Page Extractor', 'pdf', 'Extract specific pages or page ranges into a new standalone PDF.', '/pdf-extract-pages'],
    ['PDF Page Delete', 'pdf', 'Delete unnecessary pages from your PDF file effortlessly.', '/pdf-delete-pages'],
    ['PDF Grayscale Converter', 'pdf', 'Convert color PDF pages to black & white grayscale to save printer ink.', '/pdf-grayscale'],
    ['PDF Metadata Editor', 'pdf', 'Edit PDF file metadata including Title, Author, Subject, and Keywords.', '/pdf-metadata'],
    ['PDF Page Reorder', 'pdf', 'Rearrange and reorder PDF page order with drag and drop simplicity.', '/pdf-reorder'],
    ['Image Compressor', 'image', 'Compress PNG, JPG, and WebP images to reduce file size without quality loss.', '/image-compressor'],
    ['PNG to WEBP Converter', 'image', 'Convert PNG images to lightweight WebP format to speed up websites.', '/png-to-webp'],
    ['JPG to WEBP Converter', 'image', 'Convert JPEG photos into modern WebP format for fast web delivery.', '/jpg-to-webp'],
    ['Image Color Palette Extractor', 'image', 'Extract dominant color palettes and hex color codes from any image.', '/image-palette'],
    ['SVG Optimizer', 'image', 'Optimize SVG files by removing unused tags, attributes, and whitespace.', '/svg-optimizer'],
    ['Text to Image Generator', 'image', 'Create visual graphics and text images with custom fonts and colors.', '/text-to-image'],
    ['Word to Text Converter', 'docs', 'Extract raw unformatted plain text from Word (.docx) files.', '/word-to-text'],
    ['Excel to CSV Converter', 'docs', 'Convert Excel workbooks (.xlsx) to standard CSV spreadsheets.', '/excel-to-csv'],
    ['CSV to Excel Converter', 'docs', 'Convert CSV files into Microsoft Excel (.xlsx) spreadsheet workbooks.', '/csv-to-excel'],
    ['Text to Word Converter', 'docs', 'Convert plain text notes into Microsoft Word (.docx) files.', '/text-to-word'],
    ['HTML to Word Converter', 'docs', 'Convert web HTML markup into editable Word (.docx) documents.', '/html-to-word'],
    ['HTML Formatter & Sanitizer', 'dev', 'Pretty print HTML code, fix indentation, and sanitize tags.', '/html-formatter'],
    ['CSS Formatter & Beautifier', 'dev', 'Beautify CSS stylesheets, format rules, and optimize layout code.', '/css-formatter'],
    ['JS/TS Formatter', 'dev', 'Format JavaScript and TypeScript code snippets automatically.', '/js-formatter'],
    ['String Case Converter', 'dev', 'Convert text between camelCase, PascalCase, snake_case, kebab-case, and UPPERCASE.', '/case-converter'],
    ['Text Difference Checker', 'dev', 'Compare two text blocks side-by-side with exact line-by-line diffs.', '/text-diff'],
    ['Image to Text OCR', 'ocr', 'Extract editable text from images, scans, and photos using OCR.', '/image-to-text'],
    ['Handwriting OCR Scanner', 'ocr', 'Recognize handwritten text from notes and scans automatically.', '/handwriting-ocr'],
    ['Receipt & Invoice OCR', 'ocr', 'Extract vendor, totals, tax, and date details from receipts and invoices.', '/receipt-ocr'],
    ['PDF Text OCR Scanner', 'ocr', 'Convert scanned, non-searchable PDF files into searchable text PDFs.', '/pdf-ocr-text'],
    ['Multi-Language OCR Engine', 'ocr', 'Recognize and translate text across 100+ languages from images.', '/multilingual-ocr']
];

const CATEGORY_MAP = {
    pdf: 'PDF Tools',
    image: 'Image Tools',
    docs: 'Documents',
    ai: 'AI Suite',
    dev: 'Developer Tools',
    ocr: 'OCR Tools'
};

module.exports = {
    ALL_TOOLS,
    CATEGORY_MAP
};
