const sharp = require('sharp');
const path = require('path');
const fs = require('fs-extra');
const axios = require('axios');

const CATEGORY_COLORS = {
    pdf: { bg1: '#1e1b4b', bg2: '#431407', accent1: '#FF5C7A', accent2: '#FF8A5C', label: 'PDF TOOL' },
    image: { bg1: '#064e3b', bg2: '#022c22', accent1: '#22C55E', accent2: '#12B8A0', label: 'IMAGE TOOL' },
    docs: { bg1: '#1e3a8a', bg2: '#0f172a', accent1: '#3B82F6', accent2: '#6366F1', label: 'DOCUMENT TOOL' },
    ai: { bg1: '#4c1d95', bg2: '#312e81', accent1: '#8B5CF6', accent2: '#C026D3', label: 'AI SUITE' },
    dev: { bg1: '#78350f', bg2: '#451a03', accent1: '#F59E0B', accent2: '#EF4444', label: 'DEVELOPER TOOL' },
    ocr: { bg1: '#831843', bg2: '#4c1d95', accent1: '#EC4899', accent2: '#8B5CF6', label: 'OCR TOOL' }
};

/**
 * Generate a 100% AI-created visual cover image for a blog post
 * @param {string} toolName - e.g. "Merge PDF"
 * @param {string} categoryKey - e.g. "pdf", "image", "dev"
 * @param {string} slug - e.g. "how-to-merge-pdf-files-online"
 * @param {string} [aiVisualPrompt] - optional specific AI prompt generated by Gemini
 * @returns {Promise<string>} filename of saved image in uploads folder
 */
async function generateBlogCoverImage(toolName, categoryKey, slug, aiVisualPrompt = '') {
    const uploadDir = path.join(__dirname, '../uploads');
    await fs.ensureDir(uploadDir);

    const filename = `blog-cover-${slug}-${Date.now()}.png`;
    const outputPath = path.join(uploadDir, filename);

    // 1. Try 100% AI Image Generation via Pollinations AI
    try {
        console.log(`🤖 [AI Image Generator] Requesting 100% AI image model for "${toolName}"...`);
        const defaultPrompt = `high quality 3d digital artwork banner for ${toolName} ${categoryKey} tool, modern tech gradient interface, vibrant neon accents, futuristic 8k wallpaper render, cinematic lighting, sleek UI design`;
        const promptToUse = aiVisualPrompt || defaultPrompt;

        const aiImageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(promptToUse)}?width=1200&height=630&seed=${Date.now()}&nologo=true`;
        
        const response = await axios.get(aiImageUrl, {
            responseType: 'arraybuffer',
            timeout: 25000
        });

        const rawAiBuffer = Buffer.from(response.data);

        // Watermark/Brand Overlay SVG to place on the AI generated image
        const safeTitle = toolName.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
        const overlaySvg = `
        <svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <linearGradient id="brandGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" stop-color="#FF5C7A" />
                    <stop offset="100%" stop-color="#8B5CF6" />
                </linearGradient>
            </defs>
            <!-- Bottom Glassmorphism Overlay Bar -->
            <rect x="0" y="520" width="1200" height="110" fill="rgba(15, 23, 42, 0.75)" style="backdrop-filter: blur(12px);" />
            <line x1="0" y1="520" x2="1200" y2="520" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.5" />
            
            <!-- Tool Title Text -->
            <text x="50" y="570" fill="#ffffff" font-family="'Segoe UI', Arial, sans-serif" font-size="28" font-weight="800">
                ${safeTitle}
            </text>
            <text x="50" y="600" fill="#94a3b8" font-family="Arial, sans-serif" font-size="16" font-weight="600">
                Complete 2026 Online Guide &amp; Free Tool
            </text>

            <!-- Brand Badge -->
            <g transform="translate(940, 545)">
                <rect x="0" y="0" width="210" height="50" rx="14" fill="url(#brandGrad)" />
                <text x="105" y="31" text-anchor="middle" fill="#ffffff" font-family="Arial, sans-serif" font-size="17" font-weight="bold">
                    ToolBasket AI
                </text>
            </g>
        </svg>
        `;

        // Composite brand overlay on top of AI generated image
        await sharp(rawAiBuffer)
            .resize(1200, 630, { fit: 'cover' })
            .composite([{ input: Buffer.from(overlaySvg), top: 0, left: 0 }])
            .png({ quality: 90 })
            .toFile(outputPath);

        console.log(`✅ [AI Image Success] Saved 100% AI cover image: ${filename}`);
        return filename;
    } catch (aiErr) {
        console.warn('⚠️ [AI Image Fallback] Pollinations AI timed out, falling back to sharp SVG generator:', aiErr.message);
    }

    // 2. Fallback: High-res Sharp SVG Banner Generator
    const theme = CATEGORY_COLORS[categoryKey] || CATEGORY_COLORS.pdf;
    const safeTitle = toolName.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const safeSlug = slug.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

    const svgGraphic = `
    <svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
        <defs>
            <linearGradient id="bgGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stop-color="${theme.bg1}" />
                <stop offset="100%" stop-color="${theme.bg2}" />
            </linearGradient>
            <linearGradient id="accentGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stop-color="${theme.accent1}" />
                <stop offset="100%" stop-color="${theme.accent2}" />
            </linearGradient>
            <linearGradient id="glassGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stop-color="#ffffff" stop-opacity="0.08" />
                <stop offset="100%" stop-color="#ffffff" stop-opacity="0.02" />
            </linearGradient>
            <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
                <feGaussianBlur stdDeviation="40" result="blur" />
            </filter>
        </defs>
        <rect width="1200" height="630" fill="url(#bgGrad)" />
        <circle cx="1050" cy="120" r="280" fill="${theme.accent1}" opacity="0.25" filter="url(#glow)" />
        <circle cx="150" cy="520" r="240" fill="${theme.accent2}" opacity="0.2" filter="url(#glow)" />
        <rect x="80" y="80" width="1040" height="470" rx="28" fill="url(#glassGrad)" stroke="#ffffff" stroke-opacity="0.12" stroke-width="1.5" />
        <g transform="translate(130, 140)">
            <rect x="0" y="0" width="180" height="38" rx="19" fill="${theme.accent1}" fill-opacity="0.2" stroke="${theme.accent1}" stroke-opacity="0.5" stroke-width="1" />
            <text x="90" y="24" text-anchor="middle" fill="${theme.accent1}" font-family="Arial, sans-serif" font-size="13" font-weight="bold" letter-spacing="1.5">
                ${theme.label}
            </text>
        </g>
        <text x="130" y="245" fill="#ffffff" font-family="'Segoe UI', Arial, sans-serif" font-size="52" font-weight="900">
            ${safeTitle}
        </text>
        <text x="130" y="305" fill="url(#accentGrad)" font-family="'Segoe UI', Arial, sans-serif" font-size="34" font-weight="bold">
            Complete Online Guide &amp; Free Tool
        </text>
        <text x="130" y="365" fill="#94a3b8" font-family="Arial, sans-serif" font-size="20" font-weight="400">
            Fast, 100% Free, Secure &amp; No Registration Required • ToolBasket AI
        </text>
        <line x1="130" y1="415" x2="1070" y2="415" stroke="#ffffff" stroke-opacity="0.1" stroke-width="1" />
        <g transform="translate(130, 470)">
            <text x="0" y="0" fill="#64748b" font-family="Arial, sans-serif" font-size="15" font-weight="600">
                🚀 https://toolbasketai.com/${safeSlug}
            </text>
        </g>
    </svg>
    `;

    await sharp(Buffer.from(svgGraphic))
        .png({ quality: 90 })
        .toFile(outputPath);

    return filename;
}

module.exports = {
    generateBlogCoverImage
};
